"""Members — the actual gym clients.

Members do not have email/password. They authenticate to the Telegram bot
by sending a one-time linking code generated by staff. After linking,
`telegram_user_id` is set and the member can interact with the bot.
"""

import enum
from uuid import UUID

from sqlalchemy import Enum, ForeignKey, String, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base, TimestampMixin, UUIDPKMixin


class MemberStatus(str, enum.Enum):
    """Derived from membership state, not user input. We store it because
    list filtering on a computed status is painful — but we recompute on
    every check-in and via a daily Celery task."""

    ACTIVE = "active"
    FROZEN = "frozen"
    EXPIRED = "expired"
    INACTIVE = "inactive"  # no active plan, never had one or it lapsed long ago


class Member(Base, UUIDPKMixin, TimestampMixin):
    __tablename__ = "members"
    __table_args__ = (
        # Phone is unique within a tenant — same phone could belong to
        # different people across gyms.
        UniqueConstraint("tenant_id", "phone", name="uq_member_tenant_phone"),
    )

    tenant_id: Mapped[UUID] = mapped_column(
        ForeignKey("tenants.id", ondelete="CASCADE"), index=True
    )

    full_name: Mapped[str] = mapped_column(String(128))
    phone: Mapped[str] = mapped_column(String(32))
    email: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Telegram linkage. Null until member completes the linking flow.
    telegram_user_id: Mapped[int | None] = mapped_column(
        nullable=True, unique=True, index=True
    )
    # ISO 639-1 code. Defaults to tenant's default_locale on creation.
    locale: Mapped[str] = mapped_column(String(8), default="en")

    status: Mapped[MemberStatus] = mapped_column(
        Enum(MemberStatus, values_callable=lambda x: [e.value for e in x]),
        default=MemberStatus.INACTIVE,
    )

    # Optional notes from staff. Long-form free text.
    notes: Mapped[str | None] = mapped_column(String(2000), nullable=True)
